from pydantic import BaseModel, Field
from typing import List, Optional
from pydantic_xml import BaseXmlModel, element, attr

class CABEZA(BaseXmlModel):
    form: str = element(tag='FORM', default=...)
    numidentif: str = element(tag='NUMIDENTIF', default=...)
    fecvenci: str = element(tag='FECVENCI', default=...)
    adu: str = element(tag='ADU', default=...)
    agente: str = element(tag='AGENTE', default=...)
    tpodocto: str = element(tag='TPODOCTO', default=...)
    tipoingr: str = element(tag='TIPOINGR', default=...)
    numaut: str = element(tag='NUMAUT', default=...)
    fecaut: str = element(tag='FECAUT', default=...)
    gbcocen: str = element(tag='GBCOCEN', default=...)
    fectra: str = element(tag='FECTRA', default=...)
    fecacep: str = element(tag='FECACEP', default=...)
    aforo: str = element(tag='AFORO', default=...)
    fecconfdi: str = element(tag='FECCONFDI', default=...)
    numencrip: str = element(tag='NUMENCRIP', default=...)
    fecconfec: str = element(tag='FECCONFEC', default=...)
    numidenacl: str = element(tag='NUMIDENACL', default=...)
    numres: str = element(tag='NUMRES', default=...)
    fecres: str = element(tag='FECRES', default=...)
    identificacion: List['IDENTIFICACION'] = element(tag='IDENTIFICACION', default_factory=list)
    regimensuspensivo: List['REGIMENSUSPENSIVO'] = element(tag='REGIMENSUSPENSIVO', default_factory=list)
    origentranspalmacenaje: List['ORIGENTRANSPALMACENAJE'] = element(tag='ORIGENTRANSPALMACENAJE', default_factory=list)
    antecedentesfinancieros: List['ANTECEDENTESFINANCIEROS'] = element(tag='ANTECEDENTESFINANCIEROS', default_factory=list)
    totales: List['TOTALES'] = element(tag='TOTALES', default_factory=list)
    respuesta: List['RESPUESTA'] = element(tag='RESPUESTA', default_factory=list)
